name: Knip

on:
  pull_request:

permissions:
  checks: write
  issues: write

jobs:
  run-knip:
    runs-on: ubuntu-latest
    steps:

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Install toolchain
        run: yarn install

      - name: Get GitHub App token
        uses: tibdex/github-app-token@v2.1.0
        id: get_installation_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Report knip results to pull request
        uses: Codex-/knip-reporter@v2
        env:
          GITHUB_TOKEN: ${{ env.KNIP_TOKEN_FINE_GRAINED }}
        with:
          verbose: true
          comment_id: ${{ github.workflow }}-reporter
          command_script_name: knip-ci
          annotations: true
          ignore_results: false
          token: ${{ steps.get_installation_token.outputs.token }}
